CREATE TABLE IF NOT EXISTS car_showroom_single_row (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    xml_data XML NOT NULL
);

ALTER TABLE car_showroom_single_row
    OWNER TO postgres;
