-- https://postgis.net/workshops/postgis-intro/geography.html
CREATE EXTENSION postgis;

CREATE TABLE IF NOT EXISTS showrooms (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT             NOT NULL,
    city            TEXT             NOT NULL,
    street          TEXT             NOT NULL,
    building_number TEXT             NOT NULL,
    location        GEOGRAPHY(Point) NOT NULL
);

ALTER TABLE showrooms
    OWNER TO postgres;

CREATE INDEX location_index ON showrooms USING gist (location);
