CREATE TABLE IF NOT EXISTS showrooms (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT,
    city      TEXT,
    open_date TIMESTAMP
);

ALTER TABLE showrooms
    OWNER TO postgres;

-- TODO ADD INDEX !!!
