CREATE DATABASE groceryshopsdb
    WITH OWNER postgres;

CREATE TABLE IF NOT EXISTS Employees (
    Id        INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_Employees
            PRIMARY KEY,
    FirstName TEXT,
    LastName  TEXT,
    Salary    NUMERIC NOT NULL
);

ALTER TABLE Employees
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS Suppliers (
    Id                 INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_Suppliers
            PRIMARY KEY,
    Name               TEXT,
    GrossVehicleWeight REAL NOT NULL,
    EmployeeId         INTEGER
        CONSTRAINT FK_Suppliers_Employees_EmployeeId
            REFERENCES Employees
            ON DELETE RESTRICT
);

ALTER TABLE Suppliers
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS IX_Suppliers_EmployeeId
    ON Suppliers (EmployeeId);

CREATE TABLE IF NOT EXISTS Groceries (
    Id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_Groceries
            PRIMARY KEY,
    Address    TEXT,
    SupplierId INTEGER
        CONSTRAINT FK_Groceries_Suppliers_SupplierId
            REFERENCES Suppliers
            ON DELETE RESTRICT
);

ALTER TABLE Groceries
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS IX_Groceries_SupplierId
    ON Groceries (SupplierId);

CREATE TABLE IF NOT EXISTS HistoricalProducts (
    Id              INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_HistoricalProducts
            PRIMARY KEY,
    Name            TEXT,
    Amount          REAL      NOT NULL,
    Price           NUMERIC   NOT NULL,
    TransactionDate TIMESTAMP NOT NULL,
    GroceryId       INTEGER
        CONSTRAINT FK_HistoricalProducts_Groceries_GroceryId
            REFERENCES Groceries
            ON DELETE RESTRICT,
    SupplierId      INTEGER
        CONSTRAINT FK_HistoricalProducts_Suppliers_SupplierId
            REFERENCES Suppliers
            ON DELETE RESTRICT
);

ALTER TABLE HistoricalProducts
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS IX_HistoricalProducts_GroceryId
    ON HistoricalProducts (GroceryId);

CREATE INDEX IF NOT EXISTS IX_HistoricalProducts_SupplierId
    ON HistoricalProducts (SupplierId);

CREATE TABLE IF NOT EXISTS Products (
    Id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_Products
            PRIMARY KEY,
    Name       TEXT,
    Amount     REAL NOT NULL,
    GroceryId  INTEGER
        CONSTRAINT FK_Products_Groceries_GroceryId
            REFERENCES Groceries
            ON DELETE RESTRICT,
    SupplierId INTEGER
        CONSTRAINT FK_Products_Suppliers_SupplierId
            REFERENCES Suppliers
            ON DELETE RESTRICT
);

ALTER TABLE Products
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS IX_Products_GroceryId
    ON Products (GroceryId);

CREATE INDEX IF NOT EXISTS IX_Products_SupplierId
    ON Products (SupplierId);
