CREATE TABLE IF NOT EXISTS suppliers (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               TEXT,
    grossvehicleweight REAL NOT NULL,
    employeeid         INTEGER
);

ALTER TABLE suppliers
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS ix_suppliers_employeeid
    ON suppliers (employeeid);

CREATE TABLE IF NOT EXISTS boughtproduct (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT,
    amount          REAL      NOT NULL,
    price           NUMERIC   NOT NULL,
    transactiondate TIMESTAMP NOT NULL,
    supplierid      INTEGER
        CONSTRAINT fk_boughtproduct_suppliers_supplierid
            REFERENCES suppliers
            ON DELETE RESTRICT
);

ALTER TABLE boughtproduct
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS ix_boughtproduct_supplierid
    ON boughtproduct (supplierid);

CREATE TABLE IF NOT EXISTS groceries (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address    TEXT,
    supplierid INTEGER
        CONSTRAINT fk_groceries_suppliers_supplierid
            REFERENCES suppliers
            ON DELETE RESTRICT
);

ALTER TABLE groceries
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS ix_groceries_supplierid
    ON groceries (supplierid);

CREATE TABLE IF NOT EXISTS employees (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname      TEXT,
    lastname       TEXT,
    salary         NUMERIC   NOT NULL,
    employmentdate TIMESTAMP NOT NULL,
    groceryid      INTEGER
        CONSTRAINT fk_employees_groceries_groceryid
            REFERENCES groceries
            ON DELETE RESTRICT
);

ALTER TABLE employees
    OWNER TO postgres;

ALTER TABLE suppliers
    ADD CONSTRAINT fk_suppliers_employees_employeeid
        FOREIGN KEY (employeeid) REFERENCES employees
            ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS ix_employees_groceryid
    ON employees (groceryid);

CREATE TABLE IF NOT EXISTS products (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT,
    amount     REAL NOT NULL,
    groceryid  INTEGER
        CONSTRAINT fk_products_groceries_groceryid
            REFERENCES groceries
            ON DELETE RESTRICT,
    supplierid INTEGER
        CONSTRAINT fk_products_suppliers_supplierid
            REFERENCES suppliers
            ON DELETE RESTRICT
);

ALTER TABLE products
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS ix_products_groceryid
    ON products (groceryid);

CREATE INDEX IF NOT EXISTS ix_products_supplierid
    ON products (supplierid);

CREATE TABLE IF NOT EXISTS soldproduct (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT,
    amount          REAL      NOT NULL,
    price           NUMERIC   NOT NULL,
    transactiondate TIMESTAMP NOT NULL,
    groceryid       INTEGER
        CONSTRAINT fk_soldproduct_groceries_groceryid
            REFERENCES groceries
            ON DELETE RESTRICT
);

ALTER TABLE soldproduct
    OWNER TO postgres;

CREATE INDEX IF NOT EXISTS ix_soldproduct_groceryid
    ON soldproduct (groceryid);

